version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: oh-ai-gateway-postgres
    restart: always
    environment:
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: gateway
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data